AspNetCore_CanberraRestaurants_WebApp/Controllers/ReviewsForumsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using AspNetCore_CanberraRestaurants_WebApp.Data;
using AspNetCore_CanberraRestaurants_WebApp.Models;
using Microsoft.AspNetCore.Authorization.Infrastructure;
using Microsoft.AspNetCore.Authorization;

namespace AspNetCore_CanberraRestaurants_WebApp.Controllers
{
    public class ReviewsForumsController : Controller
    {
        private readonly ApplicationDbContext _context;

        public ReviewsForumsController(ApplicationDbContext context)
        {
            _context = context;
        }

        public async Task<IActionResult> Index()
        {
            return View(await _context.ReviewsForum.ToListAsync());
        }

        // GET: ReviewsForums/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var reviewsForum = await _context.ReviewsForum
                .FirstOrDefaultAsync(m => m.Id == id);
            if (reviewsForum == null)
            {
                return NotFound();
            }

            return View(reviewsForum);
        }

        // GET: ReviewsForums/Create
        [Authorize(Roles ="Manager, RegisteredUser")]
        public IActionResult Create()
        {
            ReviewsForum forum = new ReviewsForum
            {
                PostDate = DateTime.Now
            };
            return View(forum);
        }

        // POST: ReviewsForums/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles ="Manager, RegisteredUser")]
        public async Task<IActionResult> Create([Bind("Id,PostDate,UserName,Header,TopicTitle,MessageContent,Rating,Agree,Disagree")] ReviewsForum reviewsForum)
        {
            if (ModelState.IsValid)
            {
                _context.Add(reviewsForum);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(reviewsForum);
        }

        // GET: ReviewsForums/Edit/5
        [Authorize(Roles = "Manager")]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var reviewsForum = await _context.ReviewsForum.FindAsync(id);
            if (reviewsForum == null)
            {
                return NotFound();
            }
            return View(reviewsForum);
        }

        // POST: ReviewsForums/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Manager")]
        public async Task<IActionResult> Edit(int id, [Bind("Id,PostDate,UserName,Header,TopicTitle,MessageContent,Rating,Agree,Disagree")] ReviewsForum reviewsForum)
        {
            if (id != reviewsForum.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(reviewsForum);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ReviewsForumExists(reviewsForum.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(reviewsForum);
        }

        // GET: ReviewsForums/Delete/5
        [Authorize(Roles = "Manager")]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var reviewsForum = await _context.ReviewsForum
                .FirstOrDefaultAsync(m => m.Id == id);
            if (reviewsForum == null)
            {
                return NotFound();
            }

            return View(reviewsForum);
        }

        // POST: ReviewsForums/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Manager")]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var reviewsForum = await _context.ReviewsForum.FindAsync(id);
            _context.ReviewsForum.Remove(reviewsForum);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ReviewsForumExists(int id)
        {
            return _context.ReviewsForum.Any(e => e.Id == id);
        }

        public async Task<IActionResult> IncreaseAgree(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var reviewsForum = await _context.ReviewsForum.FindAsync(id);
            if (reviewsForum == null)
            {
                return NotFound();
            }
            if (ModelState.IsValid)
            {
                try
                {
                    if (User.Identity.IsAuthenticated &&
                        reviewsForum.canIncreaseAgree)
                    {
                        reviewsForum.Agree++;
                        reviewsForum.canIncreaseAgree = false;
                        reviewsForum.canIncreaseDisagree = false;
                        _context.Update(reviewsForum);
                        await _context.SaveChangesAsync();
                    }
                }

                catch (DbUpdateConcurrencyException)
                {
                    if (!ReviewsForumExists(reviewsForum.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction("Restaurants", "Home");
            }
            return RedirectToAction("Restaurants", "Home");
        }

        public async Task<IActionResult> IncreaseDisagree(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var reviewsForum = await _context.ReviewsForum.FindAsync(id);
            if (reviewsForum == null)
            {
                return NotFound();
            }
            if (ModelState.IsValid)
            {
                try
                {
                    if (User.Identity.IsAuthenticated &&
                        reviewsForum.canIncreaseDisagree)
                    {
                        reviewsForum.Disagree++;
                        reviewsForum.canIncreaseAgree = false;
                        reviewsForum.canIncreaseDisagree = false;
                        _context.Update(reviewsForum);
                        await _context.SaveChangesAsync();
                    }
                }

                catch (DbUpdateConcurrencyException)
                {
                    if (!ReviewsForumExists(reviewsForum.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction("Restaurants", "Home");
            }
            return RedirectToAction("Restaurants", "Home");
        }
    }
}

AspNetCore_CanberraRestaurants_WebApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en" xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Canberra Restaurants</title>
    <!-- Bootstrap (keep these links in the current order) -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" />
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
    <!--Stylesheet link-->
    <link href="https://fonts.googleapis.com/css?family=Niconne" rel="stylesheet" type="text/css">
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-md navbar-toggleable-md navbar-dark bg-dark box-shadow">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">
                    <span class="text-light">Canberra Restaurants</span>
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial" />
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Restaurants">Restaurants</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Cuisines">Cuisines</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Dishes">Dishes</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Prices">Prices</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Locations">Locations</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Home" asp-action="ContactAbout">Contact & About</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="ReviewsForums" asp-action="Index">Customer Reviews</a>
                        </li>

                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container-fluid">
        <main role="main">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container-fluid ml-1 mr-1">
            &copy; 2020 - Canberra Restaurants All Rights Reserved
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>